Repository wecode-bootcamp-korea/32-2nd-TerraBox-frontend, pull requests merged in 2022-05, with the labels that each got.

#6 [32기 김병규] Modify: 메인페이지 1차 작업완료 + AWS 주소로 변환
  package-lock.json
  package.json
  public/data/mock.json
  public/images/image.png
  public/images/lefticon.png
  public/images/movie1.png
  public/images/movie2.jpeg
  public/images/movie3.jpeg
  public/images/movie4.jpeg
  public/images/movie5.jpeg
  public/images/rightIcon.png
  src/pages/Main/Carousel.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#2 [32기 이형준] 예매페이지 리뷰반영, 리펙토링 중
  public/data/movie.json
  public/data/sampleData.json
  public/data/test.json
  public/data/theaters.json
  public/data/time.json
  src/pages/Booking/Booking.js
Labels: Status: Rebase 요청, Status: 리뷰 요청

#8 [32기 이나연] Add: footer 카카오 지도기능 구현 완료
  package.json
  public/index.html
  src/Router.js
  src/components/Footer.js
  src/components/FooterMap.js
Labels: Status: 리뷰 요청

#7 [32기 김병규] Add: 좌석레이아웃 및 기능 구현 중
  package-lock.json
  package.json
  public/images/MainNavLogo.png
  src/Router.js
  src/components/Nav.js
  src/pages/Login/Redirect.js
  src/pages/Main/Main.js
  src/pages/Seat/Seat.js
  src/pages/Seat/SeatButton.js
Labels: Status: 리뷰 요청

#4 [32기 박준범] 영화 상세페이지 레이아웃 구현 및 기능 작업 중
  package-lock.json
  package.json
  public/data/comment.json
  src/pages/Detail/BottomDetail.js
  src/pages/Detail/Card.js
  src/pages/Detail/Comment.js
  src/pages/Detail/CommentModal.js
  src/pages/Detail/Detail.js
  src/pages/Detail/MovieInfo.js
  src/pages/Detail/MoviePostModal.js
  src/pages/Detail/MovieRealComment.js
  src/pages/Detail/MovieVideo.js
Labels: Status: 추가 기능 구현중
